### ISSUE TITLE
奇怪的问题

### ISSUE THREAD

**Issue by lee-you** [JessYanCoding/ArmsComponent#10]
javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
                includeCompileClasspath true
            }
        }
放到 common_component_build.gradle 里老编译崩溃
![image](https://user-images.githubusercontent.com/18346188/42252163-d254b24a-7f6d-11e8-88de-c8f94df92247.png)

放到module 里面 就不会崩溃

开始以为我的java问题...我看了看我的java版本
![image](https://user-images.githubusercontent.com/18346188/42252206-1aba9950-7f6e-11e8-8147-7c2c847f810f.png)
然后环境变量也是正确的....
试了很久没解决问题...就差重做系统了

**Comment by JessYanCoding** [comment]
没遇到到过这个问题, 只有你自己解决了
