### ISSUE TITLE
不同模块下资源引用问题

### ISSUE THREAD

**Issue by yedajiang44** [JessYanCoding/ArmsComponent#13]
感谢作者对该库的贡献
我在测试的时候发现一个问题，如果我组件Test中有一个布局文件main.xml，而这时候假设宿主app中也有个相同名称main.xml时，组件Test会使用宿主app中的那个main.xml布局文件

**Comment by JessYanCoding** [comment]
所以，文档中已经写了需要给资源加上前缀，自己翻翻文档
