### ISSUE TITLE
请问一下组件化中的混淆规则是在各自module管理,还是统一在宿主app中

### ISSUE THREAD

**Issue by IurKwan** [JessYanCoding/ArmsComponent#14]

**Comment by JessYanCoding** [comment]
可能你还没理解，组件化中有开发阶段和集合调试阶段，开发阶段每个 模块 都是独立的 App，集合调试阶段所有模块都合并成为一个 App，你说在开发阶段，每个模块怎么访问 宿主？当然是每个模块直接管理自己的混淆规则，不止是混淆规则，其他所有的一切尽可能每个模块自己管理，因为每个模块都是独立的，宿主只是一个壳
