### ISSUE TITLE
重大bug

### ISSUE THREAD

**Issue by myxfeng** [JessYanCoding/ArmsComponent#15]
//用反射, 将 AndroidManifest.xml 中带有 ConfigModule 标签的 class 转成对象集合（List<ConfigModule>）
        this.mModules = new ManifestParser(context).parse();

在5.0 以下 无法启动原因   是在dex  分包的情况下 dex2 文件还未加载 就去parse 的话会报错 
所以要在parse 之前调用  MultiDex.install(context);
但是现有的框架的生命周期代理达不到要求 所以这行代码只能在框架底层加

**Comment by JessYanCoding** [comment]
**MultiDex.install(context); ** 这个代码，你自己新建一个 Application 放到 onCreate 中即可，详情请参考这个 https://www.jianshu.com/p/48523f05c569
