### ISSUE TITLE
AS3.1.2独立运行组件报错

### ISSUE THREAD

**Issue by xubo5200** [JessYanCoding/ArmsComponent#2]
isBuildModule为truer的情况下
`#isBuildModule 为 true 时可以使每个组件独立运行, false 则可以将所有组件集成到宿主 App 中
isBuildModule=true`

` dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }`
把这里改为3.0.1运行没问题3.1.2报如下错
`Could not get unknown property 'packageForR' for task ':ModuleGold:processDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.
`

**Comment by JessYanCoding** [comment]
只能用 classpath 'com.android.tools.build:gradle:3.0.1' , 主要因为 ButterKnife 的插件原因, 不能使用 v3.0.1 以上
