### ISSUE TITLE
关于数据库的疑问

### ISSUE THREAD

**Issue by IurKwan** [JessYanCoding/ArmsComponent#21]
首先感谢你的开源！
我在进行组件化拆分的时候，对于数据库的设计存在疑问。
我使用的是SQL原生数据库开发，对其进行组件拆分的时候目前只想到如下方式：

1.每个组件都维护各自一份db，其表定义在各自的组件中，但这样使用的时候每个组件都会存在一个数据 
 库实例，感觉存在性能问题。
2.独立一个数据库模块，只维护一份db，将所有的表及其操作都定义在其中，但这么做，内容都集中在一块了，感觉进行的组件化就有点变味了。
想请问下在配合该框架进行组件拆分的时候，有没更好的数据库拆分方式？

**Comment by JessYanCoding** [comment]
不好意思，很久没有接触数据库了，对此问题没有能力回答
