### ISSUE TITLE
请教个问题  butterknife 在组件化中 使用

### ISSUE THREAD

**Issue by seen2016** [JessYanCoding/ArmsComponent#23]
大神，请教个问题  butterknife 在组件化中 使用，当moudle 作为单独应用运行时 R R2 是怎么切换的？这个问题困惑我好久，还请大神指点迷津！

**Comment by JessYanCoding** [comment]
这个不是你需要考虑的，根本不需要切换，这个你可以看看我的 Demo，我 Demo 中的三个 moudle，不管是单独运行和集成宿主调试都用的 R2，都可以正常运行

**Comment by seen2016** [comment]
好的，多谢大神指点，有时间我看看你的demo！
