### ISSUE TITLE
组件之间如何相互调用model

### ISSUE THREAD

**Issue by jasonlee3652** [JessYanCoding/ArmsComponent#26]
如组件A是积分module,组件B是优惠券module,怎么让A module调用 B module中的 model,用来调用里面的某个接口获取其数据

**Comment by JessYanCoding** [comment]
这需要用到 ARouter 对外提供服务的功能，这是 [Demo 演示](https://github.com/JessYanCoding/ArmsComponent/blob/master/app/src/main/java/me/jessyan/armscomponent/app/mvp/ui/activity/MainActivity.java#L82)，这是 [官方文档](https://github.com/alibaba/ARouter/blob/master/README_CN.md)

**Comment by jasonlee3652** [comment]
谢谢，但是这种方式怎么拿到 model呢，假设 module A中有一个model类如下:
`@FragmentScope
public class LoginModel extends BaseModel implements LoginContract.Model {
    @Inject
    Gson mGson;
    @Inject
    Application mApplication;

    @Inject
    public LoginModel(IRepositoryManager repositoryManager) {
        super(repositoryManager);
    }

    @Override
    public Observable<BaseResponse<QiNiuBean>> getQiniuToken() {
        RequestBody requestBody = new ParamsBuilder(mApplication, mGson)
                .build();

        return mRepositoryManager
                .obtainRetrofitService(UserService.class)
                .getQiniuToken(requestBody);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        this.mGson = null;
        this.mApplication = null;
    }
}`

我现在有另外一个module组件B需要调用这个组件A的getQiniuToken()方法，这里需要组件A去暴露服务，我的想法是暴露的服务方法类似这样:

` public Observable<BaseResponse<QiNiuBean>> getQiniuToken()`

这样的话在module A中可以自由操作这个 observable，但是这个方法在 LoginModel 中，而且是需要绑定ui的,另外在 暴露的服务实现中，应该怎样去拿到 IRepositoryManager，从而获取 LoginModel的实例，暴露 public Observable<BaseResponse<QiNiuBean>> getQiniuToken()这个方法。希望jessYan给我一个好的建议，目前项目重构到一半，发现不同module之间很多接口都需要相互调用。

**Comment by JessYanCoding** [comment]
我觉得你应该自己先试试再问，服务分为接口和实现类，接口在公共服务中，实现类在对应的 Module 中，IRepositoryManager、LoginModel 如何调用不是你要操心的，因为实现类和它们在同一个 Module 中直接就可以调用。

公共服务中的接口 public Observable<BaseResponse<QiNiuBean>> getQiniuToken()，Observable 是在基层中就引用了的，你只用把 JavaBean 同样放到公共服务中即可，这个在 Demo 中就演示了的，你看 Demo 就能明白，事实上非常简单。

**Comment by jasonlee3652** [comment]
@JessYanCoding 多谢，我理解你的意思，但是我还是很想了解一下公共服务的实现类能做哪些事情，怎样做才是最好的方式。
我举个例子：
module A，module B 都需要用到上传图片的功能，如果使用七牛，再上传图片之前必须调用一个接口来获取七牛的 token，因为七牛的token是会失效的，每次上传图片必调用。假设我把这个接口写在了 module A 中的 AService中，它在 Fragment A 的Fragment AModel中实现，然后在 APresenter中调用，这个没问题。现在我需要将AModel 放在公共服务中去，想解决的问题是，希望module B 能调用 module A 中Fragment A 对应的Amodel 中的接口，获取新的 token。

下面是我现在想要解决的问题：

> @Route(path = RouterHub.USER.SERVICE.USER_INFO, name = "登录信息服务")
public class UserInfoServiceImpl implements UserInfoService {

    private Context mContext;

    @Inject
    AModel mModel;//我对dagger不熟,这种方式得到的mModel为null

    @Override
    public void init(Context context) {
        mContext = context;
    }

    @Override
    public boolean isLogin() {
        return UserConfig.isLogin();
    }

    @Override
    public UserBean getUserBean() {
        return UserConfig.getUser();
    }

    /**
     * 希望这个方法能调用接口,其他module 可以传一个回调参数,调用完接口将结果回调过去
     * @return
     */
    @Override
    public void getQiNiuBean(CallBack callback) {
       //调用接口
      mModel.getQiNiuBean{
      ....
        onSuccess{
            callback.success(QiNiuBean);
         }
         onError{
           callback.error(ErrorBean);
         }
    }
    }
}

我只是想module B 调用modul A 中的接口，我上面暴露服务的方式可能不对，JessYan能否给我提供一点建议?

**Comment by JessYanCoding** [comment]
建议将 七牛 ，支付宝，微信，这类给业务层提供公共服务的接口，放到业务层之上。

**Comment by jasonlee3652** [comment]
@JessYanCoding  放在宿主层吗?

**Comment by jasonlee3652** [comment]
放在 CommonSdk 或是 CommonRes 中合适否?公共服务好像是放不了了

**Comment by jasonlee3652** [comment]
或者新建一个和CommonRes同级别的module，专门用来放公共接口和Model

**Comment by JessYanCoding** [comment]
![image](https://user-images.githubusercontent.com/15711968/57577821-4c066900-74b2-11e9-859b-5471272b2afa.png)
