### ISSUE TITLE
关于使用productFlavor定义API_DOMAIN的问题

### ISSUE THREAD

**Issue by bailandi** [JessYanCoding/ArmsComponent#29]
在app的build.gralde的productFlavor里定义了API_DOMAIN后生成的BuildConfig是在app下的， 但是API_DOMAIN却是在commonSDK里用。我尝试把productFlavor定义在commonSDK下，构建的时候会报无法处理commonSDK，请问大佬有什么解决办法吗？

**Comment by JessYanCoding** [comment]
在 APP 获取到  API_DOMAIN 后，然后将 API_DOMAIN 注册给 commonSDK，APP 是能和 commonSDK 通信的，所以 commonSDK 提供一个方法就可以了

**Comment by bailandi** [comment]
好的 谢大佬！
