### ISSUE TITLE
clone项目后打开Gradle sync failed: Cause: error in opening zip file

### ISSUE THREAD

**Issue by pisfans** [JessYanCoding/ArmsComponent#3]
Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)
Re-download dependencies and sync project (requires network)

**Comment by pisfans** [comment]
根据群里说的，是gradle的问题，试了删除4.4重新下载，可以了

**Comment by JessYanCoding** [comment]
ok
