### ISSUE TITLE
因为业务需要  重写了baseActivity，但是打包的时候说这个类被定义了多次，改怎么解决呢？

### ISSUE THREAD

**Issue by z2700589** [JessYanCoding/ArmsComponent#30]
Type me.jessyan.armscomponent.commonsdk.base.IBaseActivity_MembersInjector is defined multiple times: F:\AndroidProjects\AppRepository\MobileSystem\JNRespiratory\module_system\build\intermediates\runtime_library_classes\release\classes.jar:me/jessyan/armscomponent/commonsdk/base/IBaseActivity_MembersInjector.class, F:\AndroidProjects\AppRepository\MobileSystem\JNRespiratory\module_replace\build\intermediates\runtime_library_classes\release\classes.jar:me/jessyan/armscomponent/commonsdk/base/IBaseActivity_MembersInjector.class

**Comment by kenynw** [comment]
请问最后怎么解决的呢

**Comment by z2700589** [comment]
> 请问最后怎么解决的呢

JessYanCoding/MVPArms#341

**Comment by parade0393** [comment]
> > 请问最后怎么解决的呢
> 
> [JessYanCoding/MVPArms#341](https://github.com/JessYanCoding/MVPArms/pull/341)

请问你是把base包down下来，自己又加了一个Base继承自原来的BaseActivity，然后各个module依赖你down下来经过修改过的base块吗
