### ISSUE TITLE
Unresolved reference找不到引用，但是文件是存在的

### ISSUE THREAD

**Issue by tpnet** [JessYanCoding/ArmsComponent#5]
![image](https://user-images.githubusercontent.com/17380722/40841103-dde4f6c0-65db-11e8-9002-a6f015160a5a.png)

![image](https://user-images.githubusercontent.com/17380722/40841127-f1815232-65db-11e8-82cb-f1947d702720.png)

AS: 3.1.2

**Comment by JessYanCoding** [comment]
这和这个框架并没有什么关系
