### ISSUE TITLE
RouterHub 不能自动生成路由表吗？

### ISSUE THREAD

**Issue by hongxialiu** [JessYanCoding/ArmsComponent#6]
RouterHub 不能自动生成路由表吗？不然每个组件得手动添加，太麻烦了

**Comment by JessYanCoding** [comment]
RouterHub 只是储存常量的

**Comment by hongxialiu** [comment]
其实你可能没有明白我的意思，或者我表达不是特别清楚。实际项目组件化开发过程中，组件都是相互隔离的，就是感觉手动在底层比如RouterHub写会比较麻烦，想的是这种手动写的东西，能不能自动化，比如自动生成路由表

**Comment by JessYanCoding** [comment]
我知道你的意思，我说了路由表是由 ARouter 生成, 这里只是储存常量，为什么要常量？你跳转方要知道路由地址才能跳转，你被跳转方要给 Activity 命名路由地址，并且和跳转方传入的路由地址匹配才能跳转成功，所以两个组件引用同一个常量，便于管理，降低出错率，如果你两个组件都直接使用字符串, 这就走一定的问题，路由表只是建立路由地址和 Activity 的映射关系，和这个 RouterHub 并没有关系, 你提供了正确的路由地址才能生成路由表
