### ISSUE TITLE
实际公司组件化git部署用的哪种方式

### ISSUE THREAD

**Issue by hongxialiu** [JessYanCoding/ArmsComponent#7]
你好，再麻烦问下，在实际公司组件化git部署用的哪种方式，gitsubmodule,repo,还是直接组件打包aar发布maven然后主项目引用，或者其他方式。最近再究竟选哪种方式。

**Comment by JessYanCoding** [comment]
这个我在我的文档中提及了这几种方式，也提及 Demo 仅仅是一个小型的展示，提到的更重要的一点是一定要以项目实际情况出发，不要盲目追逐大厂方案，要考虑自己的投入产出比，是否值得选择这个方案？所以我现在公司的项目用什么方式不重要，因为我公司项目的大小和类型以及开发组的构成和你的公司以及你的项目都不大有不同，我的方式并不一定适合你，并且很多文章都有介绍这些内容，只要你不搞自动化就可以很快实现，而且这里也和业务有关，只有你自己实现
