### ISSUE TITLE
使用kotlin找不到Component

### ISSUE THREAD

**Issue by tangxuesong6** [JessYanCoding/ArmsComponent#8]
通过mvp全家桶新建kotlin活动时，无法找到Component，将dagger的 annotationProcessor rootProject.ext.dependencies["dagger2-compiler"]改为 kapt rootProject.ext.dependencies["dagger2-compiler"]也没有解决

**Comment by JessYanCoding** [comment]
找不到 Component 和框架没有关系，是没有遵守 Dagger 的配置和规则导致的, 请自己认真学习 Dagger, 并且我也并没有使用 Kotlin 在项目中，也无法解决此类问题
