### ISSUE TITLE
请教下。项目组件化后，登录逻辑应该放在宿主层还是业务层？比如首页或者商城等界面，需要登录后，返回当前界面中。如何实现比较好？

### ISSUE THREAD

**Issue by Vector-SMG** [JessYanCoding/ArmsComponent#9]

**Comment by JessYanCoding** [comment]
业务的东西需要自己去解决，每个项目每个业务都不同，任何一个业务点，都可能由小变大，当然是将重要的业务都抽到业务层好，但是要自己评估自己的项目现阶段是否值得这样做，是否得到的利益大于付出的工作量
业务的实现就别问我了, 这是你的工作
